package koka.util.io.guava;

import java.io.IOException;
import java.io.OutputStream;

/**
 * Generated bytes which need to be written somewhere.
 * 
 * @since 0.5
 */
public interface ProducedData {
  /**
   * Writes contents to provided target.
   */
  void sendTo(OutputStream sink) throws IOException;
}
